name: build binary

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  go_version: "^1.17.1"
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.go_version }}

    - name: get deps
      run: |
        sudo apt-get update
        sudo apt-get install gcc libgtk-3-dev libappindicator3-dev

    - name: build binary
      run: go build

    - name: zip
      run: zip lofibar-linux.zip lofibar

    - name: upload to release
      run: gh release upload ${{ github.ref_name }} lofibar-linux.zip

  mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.go_version }}

    - name: build binary
      run: go build

    - name: zip
      run: zip lofibar-mac.zip lofibar

    - name: upload to release
      run: gh release upload ${{ github.ref_name }} lofibar-mac.zip

  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: ${{ env.go_version }}

    - name: build binary
      run: go build -ldflags "-H=windowsgui"

    - name: zip exe
      run: Compress-Archive -Path .\lofibar.exe -DestinationPath .\lofibar-windows.zip

    - name: upload to release
      run: gh release upload ${{ github.ref_name }} lofibar-windows.zip
